version: '3'
services:
  tws:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "5900:5900"
    volumes:
      - ../components/ibcontroller/IBController.ini:/root/IBController/IBController.ini
      - ../components/ibgateway/jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - VNC_PASSWORD=123456789
      - VNC_PORT=5900
      - TWSUSERID="<usr_change_me>"
      - TWSPASSWORD="<pwd_change_me>"
      - IBC_INI=/root/IBController/IBController.ini
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - TRADING_MODE=paper
      - FIXUSERID=''
      - FIXPASSWORD=''
